name: Contar arquivos HTML


on:
  workflow_dispatch:

jobs:
  contar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Contar arquivos HTML
        run: |
          echo "Contando arquivos HTML..."
          count=$(find . -name "*.html" | wc -l)
          echo "Foram encontrados $count arquivos HTML."
